# Generated by Django 3.0.6 on 2020-05-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200519_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(db_column='password', max_length=100, null=True),
        ),
    ]
