# Generated by Django 3.0.6 on 2020-05-19 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200519_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='post_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.UUIDField(db_column='user_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(db_column='email', max_length=150, null=True),
        ),
    ]
