# Generated by Django 3.0.6 on 2020-05-19 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20200519_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_id',
            field=models.CharField(blank=True, db_column='user_id', default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
