# Generated by Django 3.0.6 on 2020-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
