# Generated by Django 3.0.6 on 2020-05-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200519_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(db_column='date', max_length=100, null=True),
        ),
    ]
