# Generated by Django 3.0.6 on 2020-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20200519_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_column='date', max_length=100, null=True),
        ),
    ]
